Retrieve/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demo Ctry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indonesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iran</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Retrieve/objects/Country_Info__c.object
<CustomObject>
    <fields>
        <fullName>Do_not_mass_assign_duplicate_leads__c</fullName>
        <defaultValue>false</defaultValue>
        <description>LMT - Check to disable mass assignment of duplicate leads</description>
        <inlineHelpText>Check to disable mass assignment of duplicate leads</inlineHelpText>
        <label>Do not mass assign duplicate leads</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>It will contain the information about language used in the country</description>
        <inlineHelpText>language used in the country</inlineHelpText>
        <label>Language</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

Retrieve/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEMO Ctry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Latvia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lithuania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Morocco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Netherlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nordic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portugal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Romania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slovakia</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubType_Of_Interest__c</fullName>
        <label>SubType Of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Product Info Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TestDrive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Vehicle Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochure Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Vehicle Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End Of Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New vehicle request (business)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New vehicle request (retail)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit purchase or leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autodeclics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochure RenaultTV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochure ZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Professional VN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listing Argus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request accessory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase request ZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TypeOfInterest__c</fullName>
        <description>Type of Interest.</description>
        <label>Type of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Information - Enterprise Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Information - Personal Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APVA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APVM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RRENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSHOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VN/VO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APV-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APV-M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Retrieve/classes/LMT_LeadAcceptPreAssigned_EXT_TEST.cls
@IsTest
private class LMT_LeadAcceptPreAssigned_EXT_TEST
{
	
	public static testMethod void testAcceptPreassignation()
	{
		LMT_LeadAcceptPreAssigned_EXT ext;
		// create dealer
		Account accDealer = LMT_TestUtils_Test.createPartnerAccount('My Concession', 'my.concession@test.com');
		// create CSMO and Dealers
		User usrCsmo = LMT_TestUtils_Test.createPartnerUser('Jules', 'Cesar', accDealer); // ??
		User usrEmp1 = LMT_TestUtils_Test.createPartnerUser('Rene', 'Goscinny', accDealer);
		User usrEmp2 = LMT_TestUtils_Test.createPartnerUser('Albert', 'Uderzo', accDealer); 
		// create person account for customer
		Account acc = LMT_TestUtils_Test.createPersonAccount('Achille', 'Talon', 'a.talon@test.com', '', '', '', '3 rue des Fleurs', 'Paris', '75001', 'France');
    	// create opportunities
        String leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = :LMT_TestUtils_TEST.vn_vo_recType AND sObjectType = 'Lead'].Id;
        
        Integer nbLeads = 5;
        List<Lead> leads = new List<Lead>();
        for( Integer i = 0; i < nbLeads; i++ )
        {
        	Id preassignedSeller;
        	if( i == 1 || i == 4 )
        	{
        		preassignedSeller = usrEmp1.Id;
        	}
        	else
        	if( i == 2 )
        	{
        		preassignedSeller = usrEmp2.Id;
        	}
        	else
        	{
        		preassignedSeller = null;
        	}
        	
        	Lead lead = new Lead(
            		LastName = 'Lead'+(i+1),
            		Status = LMT_LeadUtils_CLS.leadStatus_TOASSIGN,
            		LeadSource = 'INTERNET',
            		Brand__c='RENAULT',
            		Country__c = 'France',
            		TypeOfInterest__c = 'APVA',
            		SubType_Of_Interest__c = 'Used Vehicle Request',
            		RecordTypeId = leadRecordTypeId,
            		DealerOfInterest__c = accDealer.Id,
            		OwnerId = usrCsmo.Id,
            		Preassigned_Seller__c = PreassignedSeller
            );
            
            leads.add( lead );
        }
    	insert leads;
    	
    	// dispatch
    	String[] assignableIds    = new String[]{ leads[1].Id, leads[2].Id, leads[4].Id };
    	String[] notAssignableIds = new String[]{ leads[0].Id, leads[3].Id };
    	
    	// sets current page
    	String retUrl = EncodingUtil.urlEncode( '/00Q?&page=1&rolodexIndex=-1', 'UTF-8' );
    	PageReference p = Page.LMT_LeadAcceptPreAssigned;
    	p.getParameters().put( 'retURL', retUrl );
    	Test.setCurrentPage( p );
    	
		// run test
		Test.startTest();
		System.runAs( usrCsmo )
		{
			// creates standard set controller
			ApexPages.StandardSetController sc = new ApexPages.Standardsetcontroller( leads );
			sc.setSelected( leads ); 
			// creates controller
			ext = new LMT_LeadAcceptPreAssigned_EXT( sc );
			// assertions
			System.assertNotEquals( null, ext.assignableLeads );
			System.assertEquals( 3, ext.assignableLeads.size() );
			LMT_TestUtils_Test.assertListContainsIds( assignableIds, ext.assignableLeads );
			System.assertNotEquals( null, ext.notassignableLeads );
			System.assertEquals( 2, ext.notassignableLeads.size() );
			LMT_TestUtils_Test.assertListContainsIds( notAssignableIds, ext.notassignableLeads );
			// accepts assignation
			PageReference ret = ext.accept();
			System.assertNotEquals( null, ret );
			System.assertEquals( retUrl, ret.getUrl() );
		}
		Test.stopTest();
		
		// check test
		List<Lead> leadRecords = [SELECT OwnerId FROM Lead WHERE Id IN :leads];
		System.assertEquals( nbLeads, leadRecords.size() );
		for( Lead o : leadRecords )
		{
			if( o.Id == leads[0].Id || o.Id == leads[3].Id )
			{
				System.assertEquals( usrCsmo.Id, o.OwnerId );
			}
			else
			if( o.Id == leads[1].Id || o.Id == leads[4].Id )
			{
				System.assertEquals( usrEmp1.Id, o.OwnerId );
			}
			else
			if( o.Id == leads[2].Id )
			{
				System.assertEquals( usrEmp2.Id, o.OwnerId );
			}
			else
			{
			}
		}
	}
	
	public static testMethod void testAcceptPreassignationWithCustomIds()
	{
		LMT_LeadAcceptPreAssigned_EXT ext;
		// create dealer
		Account accDealer = LMT_TestUtils_Test.createPartnerAccount('My Concession', 'my.concession@test.com');
		// create CSMO and Dealers
		User usrCsmo = LMT_TestUtils_Test.createPartnerUser('Jules', 'Cesar', accDealer); // ??
		User usrEmp1 = LMT_TestUtils_Test.createPartnerUser('Rene', 'Goscinny', accDealer);
		User usrEmp2 = LMT_TestUtils_Test.createPartnerUser('Albert', 'Uderzo', accDealer); 
		// create person account for customer
		Account acc = LMT_TestUtils_Test.createPersonAccount('Achille', 'Talon', 'a.talon@test.com', '', '', '', '10 rue de la Vie', 'Paris', '75001', 'France');
    	// create opportunities
        String leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = :LMT_TestUtils_TEST.vn_vo_recType AND sObjectType = 'Lead'].Id;
        
        Integer nbLeads = 5;
        List<Lead> leads = new List<Lead>();
        for( Integer i = 0; i < nbLeads; i++ )
        {
        	Id preassignedSeller;
        	if( i == 1 || i == 4 )
        	{
        		preassignedSeller = usrEmp1.Id;
        	}
        	else
        	if( i == 2 )
        	{
        		preassignedSeller = usrEmp2.Id;
        	}
        	else
        	{
        		preassignedSeller = null;
        	}
        	
        	Lead lead = new Lead(
            		LastName = 'Lead'+(i+1),
            		Status = LMT_LeadUtils_CLS.leadStatus_TOASSIGN,
            		LeadSource = 'INTERNET',
            		Brand__c='RENAULT',
            		Country__c = 'France',
            		TypeOfInterest__c = 'APVA',
            		SubType_Of_Interest__c = 'Used Vehicle Request',
            		RecordTypeId = leadRecordTypeId,
            		DealerOfInterest__c = accDealer.Id,
            		OwnerId = usrCsmo.Id,
            		Preassigned_Seller__c = PreassignedSeller
            );
            
            leads.add( lead );
        }
    	insert leads;
    	
    	// dispatch
    	String[] assignableIds    = new String[]{ leads[1].Id, leads[2].Id, leads[4].Id };
    	String[] notAssignableIds = new String[]{ leads[0].Id, leads[3].Id };
    	
    	// sets current page
    	String retUrl = EncodingUtil.urlEncode( '/00Q?&page=1&rolodexIndex=-1', 'UTF-8' );
    	PageReference p = Page.LMT_LeadAcceptPreAssigned;
    	p.getParameters().put( 'retURL', retUrl );
    	Test.setCurrentPage( p );
    	
		// run test
		Test.startTest();
		System.runAs( usrCsmo )
		{
			// creates standard set controller
			ApexPages.StandardSetController sc = new ApexPages.Standardsetcontroller( leads );
			//sc.setSelected( leads ); 
			
			String customIds = '';
			for( Lead lead : leads )
			{
				if( !String.isEmpty( customIds ) )
				{
					customIds += ',';
				}
				customIds += lead.Id;
			}
			p.getParameters().put( 'customids', customIds );
			
			// creates controller
			ext = new LMT_LeadAcceptPreAssigned_EXT( sc );
			// assertions
			System.assertNotEquals( null, ext.assignableLeads );
			System.assertEquals( 3, ext.assignableLeads.size() );
			LMT_TestUtils_Test.assertListContainsIds( assignableIds, ext.assignableLeads );
			System.assertNotEquals( null, ext.notassignableLeads );
			System.assertEquals( 2, ext.notassignableLeads.size() );
			LMT_TestUtils_Test.assertListContainsIds( notAssignableIds, ext.notassignableLeads );
			// accepts assignation
			PageReference ret = ext.accept();
			System.assertNotEquals( null, ret );
			System.assertEquals( retUrl, ret.getUrl() );
		}
		Test.stopTest();
		
		// check test
		List<Lead> leadRecords = [SELECT OwnerId FROM Lead WHERE Id IN :leads];
		System.assertEquals( nbLeads, leadRecords.size() );
		for( Lead o : leadRecords )
		{
			if( o.Id == leads[0].Id || o.Id == leads[3].Id )
			{
				System.assertEquals( usrCsmo.Id, o.OwnerId );
			}
			else
			if( o.Id == leads[1].Id || o.Id == leads[4].Id )
			{
				System.assertEquals( usrEmp1.Id, o.OwnerId );
			}
			else
			if( o.Id == leads[2].Id )
			{
				System.assertEquals( usrEmp2.Id, o.OwnerId );
			}
			else
			{
			}
		}
	}
	
	public static testMethod void testDuplicateLeadsPreassignation()
	{
        Country_Info__c cs = new Country_Info__c(Name='France', Language__c='French', Do_not_mass_assign_duplicate_leads__c=false);
        insert cs;
		
		LMT_LeadAcceptPreAssigned_EXT ext;
		// create dealer
		Account accDealer = LMT_TestUtils_Test.createPartnerAccount('My Concession', 'my.concession@test.com');
		// create CSMO and Dealers
		User usrCsmo = LMT_TestUtils_Test.createPartnerUser('Jules', 'Cesar', accDealer, LMT_TestUtils_Test.csmo_profile); 
		User usrEmp1 = LMT_TestUtils_Test.createPartnerUser('Rene', 'Goscinny', accDealer, LMT_TestUtils_Test.dealer_profile);
		// create person account for customer
		Account acc = LMT_TestUtils_Test.createPersonAccount('Achille', 'Talon', 'a.talon@test.com', '', '', '', '3 rue des Fleurs', 'Paris', '75001', 'France');
    	// create opportunities
        String leadRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = :LMT_TestUtils_TEST.vn_vo_recType AND sObjectType = 'Lead'].Id;
        
        Lead[] leads = new List<Lead>();
        List<Id> lleadIds = new List<Id>();
        for (Integer i = 1; i <= 3; i++){
	    	leads.add(new Lead(LastName = 'Lead Father', Status = LMT_LeadUtils_CLS.leadStatus_TOASSIGN, LeadSource = 'INTERNET',
	        		Brand__c='RENAULT', Country__c = 'France', TypeOfInterest__c = 'APVA', SubType_Of_Interest__c = 'Used Vehicle Request',
	        		RecordTypeId = leadRecordTypeId, DealerOfInterest__c = accDealer.Id, OwnerId = usrCsmo.Id, Preassigned_Seller__c = usrEmp1.Id));
        }    
    	insert leads;
    	
    	for (Lead l : leads){
    		l.OwnerId = usrCsmo.Id;
    		lleadIds.add(l.Id);
    	}
    	update leads;
    	
        List<Lead> leadEnfants = new List<Lead>();
        for (Integer i =1; i<= 4; i++){
	    	leadEnfants.add(new Lead(LastName = 'Lead Child' + i, Status = LMT_LeadUtils_CLS.leadStatus_CLOSED, LeadSource = 'INTERNET',
	        		Brand__c='RENAULT', Country__c = 'France', TypeOfInterest__c = 'APVA', SubType_Of_Interest__c = 'Used Vehicle Request',
	        		RecordTypeId = leadRecordTypeId, DealerOfInterest__c = accDealer.Id, OwnerId = usrCsmo.Id, Parent_Lead__c = leads[0].Id));
        }
        insert leadEnfants;
        
    	for (Lead l : [SELECT Id, OwnerId FROM Lead WHERE Id = :leadEnfants]){
    		l.OwnerId = usrCsmo.Id;
    	}
    	update leadEnfants;
        
        //-- a child lead owned by current user that should not be seen by the csmo
    	Lead unreadableLead = new Lead(LastName = 'Lead Child Unredeable', Status = LMT_LeadUtils_CLS.leadStatus_CLOSED, LeadSource = 'INTERNET',
        		Brand__c='RENAULT', Country__c = 'France', TypeOfInterest__c = 'APVA', SubType_Of_Interest__c = 'Used Vehicle Request',
        		RecordTypeId = leadRecordTypeId, DealerOfInterest__c = accDealer.Id, OwnerId = UserInfo.getUserId(), Parent_Lead__c = leads[0].Id);
        insert unreadableLead;
        
        unreadableLead = [SELECT Id, OwnerId FROM Lead WHERE Id = :unreadableLead.Id];
        
    	// sets current page
    	String retUrl = EncodingUtil.urlEncode( '/00Q?&page=1&rolodexIndex=-1', 'UTF-8' );
    	PageReference p = Page.LMT_LeadAcceptPreAssigned;
    	p.getParameters().put( 'retURL', retUrl );
    	Test.setCurrentPage( p );
    	
		// run test
		Test.startTest();
		System.runAs( usrCsmo )
		{
			// creates standard set controller
			ApexPages.StandardSetController sc = new ApexPages.Standardsetcontroller( leads );
			sc.setSelected( leads ); 
			// creates controller
			ext = new LMT_LeadAcceptPreAssigned_EXT( sc );
			// assertions
			System.assertNotEquals( null, ext.assignableLeads );
			System.assertEquals( 3, ext.assignableLeads.size() );
			LMT_TestUtils_Test.assertListContainsIds( lleadIds, ext.assignableLeads );
			// accepts assignation
			PageReference ret = ext.accept();
			System.assertNotEquals( null, ret );
			System.assertEquals( retUrl, ret.getUrl() );
		}
		Test.stopTest();
		
		// check test
		List<Lead> leadRecords = [SELECT OwnerId FROM Lead WHERE Id IN :leads];
		for (Lead l : leadRecords){
			System.assertEquals(usrEmp1.Id, l.OwnerId);
		}
		leadRecords = [SELECT OwnerId FROM Lead WHERE Id IN :leadEnfants];
		for (Lead l : leadRecords){
			if (l.Id == unreadableLead.Id){
				System.assertEquals(unreadableLead.OwnerId, l.OwnerId);
			}else{
				System.assertEquals(usrEmp1.Id, l.OwnerId);
			}
		}
	}	
}