Retrieve/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CountryCase__c</fullName>
        <label>Country Case</label>
        <picklist>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEMO Cntry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indonesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iran</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Retrieve/classes/TaskTriggerHandlerforRforce_Test.cls
/*****************************************************************************************
    Name    : TaskTriggerHandlerforRforce_Test
    Desc    :
    Approach:
    Author  : Rajavel B(RNTBCI)
    Project : Rforce
******************************************************************************************/
@isTest(SeeAllData=true)

public with sharing class TaskTriggerHandlerforRforce_Test {

    private static testMethod void testTrigger() {
    Account acc = new Account(Name='test');
    List<RecordType> listRT = [SELECT Id From RecordType WHERE sobjecttype='Task'];
    //just to have a minimal code coverage for task_afterdelete_trigger
    Case cs = new case (Type='Complaint', Origin='RENAULT SITE', AccountId=acc.Id, Status='New', Description='Test', CountryCase__c='France');
        insert cs;
        acc.CaseNumber__c = cs.id;
       // update acc;
        
    Task tsk1 = new Task(
          Subject = 'Test Trigger',
          Type = '',
          Priority = 'Normal',
          Status = 'To Do',
          OwnerId = UserInfo.getUserId(),
          WhoId = acc.Id,
          whatId = cs.Id,
          recordtypeid = listRT[0].Id
          );
   // Rforce_CheckRecursive_Utility.hasAlreadyUpdated();      
    insert tsk1;
    
    
         Attachment att = new Attachment();        
        att.Name = 'TestValue';
        att.IsPrivate = False;
        att.OwnerId = UserInfo.getUserId();
        att.ParentId = tsk1.id ;
        att.Body = Blob.valueOf('Test Body');        
        insert att;
        tsk1.Subject = 'TEST 123';
        try{
      //  Rforce_CheckRecursive_Utility.hasAlreadyUpdated();
        update tsk1;
        }catch(Exception e) {                  
              } 
          try {
                  delete att;    
              }
              catch(Exception e) {                  
              }          
    
  }
}